app: telegram-huggingface-bot  # Remplacez par le vrai nom de votre app Koyeb
services:
  - name: telegram-bot
    type: web
    ports:
      - port: 8080
        http_path: /
    scaling:
      min: 1
      max: 1  # Obligatoire pour éviter les conflits Telegram
    routes:
      - path: /
        port: 8080
    env:
       - key: WEBHOOK_URL
        value: "https://isticharabot-koyeb.app/webhook" # À remplacer
    http_healthcheck:
      path: /
      port: 8080
      interval: 30s
      timeout: 3s
      success_threshold: 1
      failure_threshold: 3
    build:
      args:
        BP_PYTHON_VERSION: "3.11.8"  # Force la version Python
      command: gunicorn --bind :$PORT --workers 1 --timeout 120 main:app
      
git:
  branch: main
  repository: zouhayr/telegram-huggingface-bot
  provider: github
